### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by designerMichael** [githubwing/GankClient-Kotlin#2]
java.lang.annotation.IncompleteAnnotationException: android.databinding.BindingBuildInfo missing element enableDebugLogs
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:81)
	at com.sun.proxy.$Proxy133.enableDebugLogs(Unknown Source)
	at android.databinding.annotationprocessor.BuildInfoUtil.load(BuildInfoUtil.java:35)
	at android.databinding.annotationprocessor.ProcessDataBinding.process(ProcessDataBinding.java:57)
	at org.jetbrains.kotlin.annotation.AbstractAnnotationProcessingExtension.doRound(AnnotationProcessingExtension.kt:312)
	at org.jetbrains.kotlin.annotation.AbstractAnnotationProcessingExtension.process(AnnotationProcessingExtension.kt:252)
	at org.jetbrains.kotlin.annotation.AbstractAnnotationProcessingExtension.doAnnotationProcessing(AnnotationProcessingExtension.kt:239)
	at org.jetbrains.kotlin.annotation.AbstractAnnotationProcessingExtension.analysisCompleted(AnnotationProcessingExtension.kt:131)
	at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.java:160)
	at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegrationWithCustomContext(TopDownAnalyzerFacadeForJVM.java:79)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.analyze(KotlinToJVMBytecodeCompiler.kt:362)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:126)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:355)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:130)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:183)

**Comment by cxy200927099** [comment]
这个问题是由于dataBinding的版本需要与gradle的版本保持一致
参见：https://issuetracker.google.com/issues/37126648
但是我还遇到其他问题，还是报dataBinding的错误

**Comment by xiang473535976** [comment]
编译错误    没法运行

**Comment by robbenv** [comment]
编译的时候不要根据android studio的提示去升级gradle plugin,编译就不会报错,至于为什么这样我也不清楚

**Comment by githubwing** [comment]
测试最新版的3.0可以编译，更新studio再试下~
